"use client";

import { Check, ChevronLeft, ChevronRight, Upload } from "lucide-react";
import { FormEvent, useState } from "react";
import { whatsappUrl } from "@/lib/constants";
import { useWizardStore } from "@/lib/store";
import type { Locale } from "@/types";

const projectOptions = [
  ["Sofa or seating", "أريكة أو جلسة"], ["Bed or headboard", "سرير أو لوح رأس"],
  ["Wardrobe or storage", "خزانة أو وحدة تخزين"], ["Dining or table", "طاولة طعام أو طاولة"], ["Other piece", "قطعة أخرى"],
] as const;
const materialOptions = [
  ["Walnut", "جوز", "/images/catalog/wall-tv-unit.webp"], ["Oak", "بلوط", "/images/catalog/wardrobe-cabinet.webp"],
  ["Boucle", "بوكليه", "/images/catalog/custom-sofa-chair.webp"], ["Linen", "كتان", "/images/catalog/linen-curtains.webp"],
  ["Velvet", "مخمل", "/images/catalog/velvet-curtains.webp"], ["Leather", "جلد", "/images/catalog/chair-upholstery.webp"],
  ["Stone", "حجر", "/images/catalog/washrooms/natural-stone-look-tiles.webp"], ["Brass", "نحاس", "/images/catalog/kitchens/glass-detail-kitchen-cabinetry.webp"],
] as const;

export function CustomFurnitureWizard({ locale = "en" }: { locale?: Locale }) {
  const ar = locale === "ar", state = useWizardStore(), [sent, setSent] = useState(false);
  const t = (en: string, arabic: string) => ar ? arabic : en;
  const stepNames = ar ? ["المشروع", "الخامات", "التفاصيل", "المراجع", "بياناتك"] : ["Project", "Materials", "Details", "References", "About you"];
  const toggleMaterial = (value: string) => state.update({ materials: state.materials.includes(value) ? state.materials.filter((item) => item !== value) : [...state.materials, value] });
  const submit = (event: FormEvent) => { event.preventDefault(); setSent(true); };
  if (sent) return <div className="surface-card rounded-3xl px-6 py-20 text-center" dir={ar ? "rtl" : "ltr"}><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-sage text-charcoal"><Check /></span><h3 className="mt-6 text-3xl font-medium">{t("Your brief is ready.", "موجز مشروعك جاهز.")}</h3><p className="mx-auto mt-3 max-w-md text-black/60">{ar ? `شكراً لك، ${state.name}. سيتواصل معك مستشار تصميم من NESTRO لتطوير التفاصيل وترتيب الخطوة التالية.` : `Thank you, ${state.name}. A NESTRO design advisor will contact you to refine the details and arrange the next step.`}</p><a href={whatsappUrl(ar ? `مرحباً NESTRO، أكملت للتو موجز أثاث حسب الطلب لمشروع ${state.projectType}.` : `Hello NESTRO, I have just completed a custom furniture brief for ${state.projectType}.`)} target="_blank" rel="noreferrer" className="button button-primary mt-8">{t("Continue on WhatsApp", "تابع عبر واتساب")}</a></div>;
  const StepLabel = ({ number }: { number: number }) => <p className="eyebrow">{ar ? `الخطوة ${number} من 5` : `Step ${number} of 5`}</p>;
  return <form onSubmit={submit} className="surface-card rounded-3xl p-5 md:p-9" dir={ar ? "rtl" : "ltr"}>
    <div className="grid grid-cols-5 gap-2">{stepNames.map((name, index) => <div key={name}><div className={`h-1 rounded-full ${index + 1 <= state.step ? "bg-sage" : "bg-black/10"}`} /><span className="mt-2 hidden text-[10px] font-bold uppercase tracking-[.1em] text-black/45 sm:block">{name}</span></div>)}</div>
    <div key={state.step} className="wizard-step min-h-[380px] py-10">
      {state.step === 1 && <><StepLabel number={1} /><h3 className="mt-5 text-3xl font-medium">{t("What would you like to create?", "ما الذي تود تصميمه؟")}</h3><div className="mt-8 grid gap-3 sm:grid-cols-2">{projectOptions.map(([value, label]) => <button type="button" key={value} onClick={() => state.update({ projectType: value })} className={`rounded-2xl border p-5 text-start transition ${state.projectType === value ? "border-brand bg-brand text-charcoal shadow-sm" : "fine-border hover:border-brand"}`}>{ar ? label : value}</button>)}</div></>}
      {state.step === 2 && <><StepLabel number={2} /><h3 className="mt-5 text-3xl font-medium">{t("Which materials speak to you?", "أي الخامات تعبّر عن ذوقك؟")}</h3><p className="mt-3 text-sm text-black/55">{t("Choose as many as you like. We’ll help refine the palette.", "اختر ما تشاء، وسنساعدك على تنسيق مجموعة الخامات.")}</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{materialOptions.map(([value, label, image]) => { const selected = state.materials.includes(value); return <button type="button" key={value} aria-pressed={selected} onClick={() => toggleMaterial(value)} className={`material-choice group relative aspect-square overflow-hidden rounded-2xl border text-start ${selected ? "is-selected" : ""}`}><span aria-hidden="true" className="absolute inset-0 bg-cover bg-center transition duration-500 group-hover:scale-105" style={{ backgroundImage: `url(${image})` }} /><span aria-hidden="true" className="material-choice-overlay absolute inset-0" /><span className="absolute inset-x-3 bottom-3 flex items-center justify-between gap-2 rounded-xl bg-ivory/90 px-3 py-2 text-sm font-bold text-charcoal shadow-sm backdrop-blur-sm"><span>{ar ? label : value}</span>{selected && <Check size={16} strokeWidth={2.5} />}</span></button>; })}</div></>}
      {state.step === 3 && <><StepLabel number={3} /><h3 className="mt-5 text-3xl font-medium">{t("Share the practical details.", "شاركنا التفاصيل العملية.")}</h3><div className="mt-8 grid gap-5"><label className="text-sm">{t("Approximate dimensions", "الأبعاد التقريبية")}<textarea value={state.dimensions} onChange={(event) => state.update({ dimensions: event.target.value })} placeholder={t("Width × depth × height, or tell us about the available space", "العرض × العمق × الارتفاع، أو أخبرنا عن المساحة المتاحة")} className="mt-2 min-h-28 w-full rounded-xl border fine-border bg-ivory p-4" /></label><label className="text-sm">{t("Style direction", "اتجاه التصميم")}<select value={state.style} onChange={(event) => state.update({ style: event.target.value })} className="mt-2 w-full rounded-xl border fine-border bg-ivory p-4"><option value="">{t("Select a direction", "اختر اتجاهاً")}</option>{[["Warm minimal", "بساطة دافئة"], ["Contemporary", "معاصر"], ["Classic tailored", "كلاسيكي أنيق"], ["Organic modern", "عضوي معاصر"], ["Not sure yet", "لم أحدد بعد"]].map(([value, label]) => <option key={value} value={value}>{ar ? label : value}</option>)}</select></label></div></>}
      {state.step === 4 && <><StepLabel number={4} /><h3 className="mt-5 text-3xl font-medium">{t("Add a reference, if you have one.", "أضف مرجعاً إن توفر لديك.")}</h3><label className="mt-8 grid min-h-52 cursor-pointer place-items-center rounded-2xl border border-dashed border-sage/50 bg-ivory text-center"><div><Upload className="mx-auto text-sage" /><strong className="mt-4 block">{t("Upload a photo or floor plan", "ارفع صورة أو مخططاً")}</strong><span className="mt-1 block text-xs text-black/45">{t("JPG, PNG or PDF · preview only", "JPG أو PNG أو PDF · للمعاينة فقط")}</span>{state.reference && <span className="mt-3 block text-xs font-semibold text-sage" dir="ltr">{state.reference}</span>}</div><input type="file" accept="image/*,.pdf" className="sr-only" onChange={(event) => state.update({ reference: event.target.files?.[0]?.name || "" })} /></label></>}
      {state.step === 5 && <><StepLabel number={5} /><h3 className="mt-5 text-3xl font-medium">{t("Where should we continue?", "كيف يمكننا التواصل معك؟")}</h3><div className="mt-8 grid gap-4 sm:grid-cols-2">{[["name", "Name", "الاسم", "text"], ["phone", "Phone", "الهاتف", "tel"], ["email", "Email", "البريد الإلكتروني", "email"]].map(([field, en, arabic, type]) => <label key={field} className="text-sm">{t(en, arabic)}<input required type={type} dir={field === "name" ? undefined : "ltr"} value={state[field as "name" | "phone" | "email"]} onChange={(event) => state.update({ [field]: event.target.value })} className="mt-2 w-full rounded-xl border fine-border bg-ivory p-4" /></label>)}<label className="text-sm">{t("UAE location", "الموقع في الإمارات")}<select required value={state.location} onChange={(event) => state.update({ location: event.target.value })} className="mt-2 w-full rounded-xl border fine-border bg-ivory p-4"><option value="">{t("Select Emirate", "اختر الإمارة")}</option>{[["Dubai", "دبي"], ["Abu Dhabi", "أبوظبي"], ["Sharjah", "الشارقة"], ["Ajman", "عجمان"], ["Ras Al Khaimah", "رأس الخيمة"], ["Fujairah", "الفجيرة"], ["Umm Al Quwain", "أم القيوين"]].map(([value, label]) => <option key={value} value={value}>{ar ? label : value}</option>)}</select></label></div></>}
    </div>
    <div className="flex items-center justify-between border-t fine-border pt-5"><button type="button" disabled={state.step === 1} onClick={() => state.setStep(state.step - 1)} className="button button-outline disabled:cursor-not-allowed disabled:opacity-30"><ChevronLeft className={ar ? "rotate-180" : ""} size={17} /> {t("Back", "السابق")}</button>{state.step < 5 ? <button type="button" disabled={state.step === 1 && !state.projectType} onClick={() => state.setStep(state.step + 1)} className="button button-primary disabled:opacity-40">{t("Continue", "متابعة")} <ChevronRight className={ar ? "rotate-180" : ""} size={17} /></button> : <button className="button button-primary">{t("Send my brief", "أرسل موجز المشروع")} <ChevronRight className={ar ? "rotate-180" : ""} size={17} /></button>}</div>
  </form>;
}
