import type { CatalogOffering, Locale, LocalizedText, PricingOption } from "@/types";

const t = (en: string, ar: string): LocalizedText => ({ en, ar });
const roomArabic: Record<string, string> = {
  "All rooms": "كل الغرف", "Living room": "غرفة المعيشة", Bedroom: "غرفة النوم", "Dining room": "غرفة الطعام",
  Office: "المكتب", Majlis: "المجلس", Kitchen: "المطبخ", Bathroom: "الحمام", Nursery: "غرفة الأطفال",
  "Kids room": "غرفة الأطفال", "Home theater": "المسرح المنزلي", Hotel: "الفندق", Patio: "الفناء",
  Terrace: "التراس", Garden: "الحديقة", Balcony: "الشرفة", Poolside: "منطقة المسبح", Apartment: "الشقة",
  Pantry: "المخزن", Ensuite: "حمام داخلي", "Powder room": "حمام الضيوف", "Shower room": "غرفة الاستحمام",
  "Shower niche": "تجويف الاستحمام", "Media room": "غرفة الوسائط", "Dressing room": "غرفة الملابس",
};
const option = (en: string, ar: string, pricePerSqm: number, minimumBill: number, motorized = false): PricingOption => ({ label: t(en, ar), pricePerSqm, minimumBill, motorized });

type Seed = {
  slug: string; collection: CatalogOffering["collection"]; en: string; ar: string; sub: string;
  rooms: string[]; materials: [string, string][]; options?: PricingOption[]; motor?: boolean; featured?: boolean;
  summary?: LocalizedText; description?: LocalizedText; images?: string[];
};

const blindMaterials: [string, string][] = [["Blackout", "تعتيم"], ["Sunscreen", "حماية شمسية"], ["Voile", "فوال"], ["Jacquard", "جاكار"]];
const curtainMaterials: [string, string][] = [["Linen finish", "تشطيب كتاني"], ["Velvet", "مخمل"], ["Cotton", "قطن"], ["Voile", "فوال"], ["Blackout", "تعتيم"]];
const indoorMaterials: [string, string][] = [["Performance fabric", "قماش عالي الأداء"], ["Velvet", "مخمل"], ["Bouclé", "بوكلية"], ["High-density foam", "إسفنج عالي الكثافة"]];
const outdoorMaterials: [string, string][] = [["Outdoor acrylic", "أكريليك خارجي"], ["Solution-dyed fabric", "قماش مصبوغ بالمحلول"], ["Quick-dry foam", "إسفنج سريع الجفاف"], ["Water-resistant cover", "غطاء مقاوم للماء"]];

const seeds: Seed[] = [
  { slug:"custom-bed-headboard", collection:"custom-furniture", en:"Custom Bed & Headboard", ar:"سرير ولوح رأس حسب الطلب", sub:"Bedroom", rooms:["Bedroom"], materials:[["Solid timber","خشب صلب"],["Veneer","قشرة خشبية"],["Upholstery fabric","قماش تنجيد"],["Metal detailing","تفاصيل معدنية"]], featured:true },
  { slug:"custom-sofa-chair", collection:"custom-furniture", en:"Custom Sofa & Chair", ar:"أريكة وكرسي حسب الطلب", sub:"Living", rooms:["Living room","Majlis"], materials:indoorMaterials },
  { slug:"wall-tv-unit", collection:"custom-furniture", en:"Wall & TV Unit", ar:"وحدة جدارية وتلفاز", sub:"Living", rooms:["Living room","Media room"], materials:[["Veneer","قشرة خشبية"],["MDF","ألواح إم دي إف"],["Natural stone","حجر طبيعي"],["Metal","معدن"]] },
  { slug:"wardrobe-cabinet", collection:"custom-furniture", en:"Wardrobe & Cabinet", ar:"خزانة ووحدة تخزين", sub:"Storage", rooms:["Bedroom","Dressing room"], materials:[["MDF","ألواح إم دي إف"],["Veneer","قشرة خشبية"],["Glass","زجاج"],["Metal","معدن"]] },

  { slug:"roller-blinds", collection:"blinds", en:"Roller Blinds", ar:"ستائر رول", sub:"Blinds", rooms:["Bedroom","Living room","Office"], materials:blindMaterials, motor:true, featured:true, options:[option("Blackout","تعتيم",95,380),option("Sunscreen","حماية شمسية",95,380),option("Motorized","آلية بمحرك",200,800,true)] },
  { slug:"duplex-blinds", collection:"blinds", en:"Duplex Blinds (Zebra)", ar:"ستائر دوبلكس (زيبرا)", sub:"Blinds", rooms:["Living room","Office","Bedroom"], materials:blindMaterials, motor:true, options:[option("Standard","قياسي",120,480),option("Motorized","آلية بمحرك",200,800,true)] },
  { slug:"sheer-horizontal-blinds", collection:"blinds", en:"Sheer Horizontal Blinds", ar:"ستائر أفقية شفافة", sub:"Blinds", rooms:["Living room","Dining room","Bedroom"], materials:[["Sheer fabric","قماش شفاف"],["Fabric vanes","شرائح قماشية"]], motor:true, options:[option("Standard","قياسي",120,480)] },
  { slug:"bamboo-blinds", collection:"blinds", en:"Bamboo Blinds", ar:"ستائر بامبو", sub:"Natural blinds", rooms:["Living room","Patio","Bathroom"], materials:[["Natural bamboo","بامبو طبيعي"],["Carbonized bamboo","بامبو مكربن"],["Painted bamboo","بامبو مطلي"]], options:[option("Standard","قياسي",180,720)] },
  { slug:"vertical-blinds", collection:"blinds", en:"Vertical Blinds", ar:"ستائر عمودية", sub:"Blinds", rooms:["Office","Living room"], materials:[["Fabric","قماش"],["PVC","بولي فينيل كلوريد"],["Aluminium","ألمنيوم"]], motor:true, options:[option("Standard","قياسي",95,300)] },
  { slug:"aluminium-venetian-blinds", collection:"blinds", en:"Aluminium Venetian Blinds", ar:"ستائر فينيسية ألمنيوم", sub:"Blinds", rooms:["Office","Kitchen","Bathroom"], materials:[["Aluminium","ألمنيوم"]], options:[option("Standard","قياسي",95,300)] },
  { slug:"panel-blinds", collection:"blinds", en:"Panel Blinds", ar:"ستائر بانل", sub:"Blinds", rooms:["Living room","Office"], materials:[["Screen fabric","قماش سكرين"],["Blackout fabric","قماش تعتيم"]], motor:true, options:[option("Standard","قياسي",180,720)] },
  { slug:"wooden-blinds", collection:"blinds", en:"Wooden Blinds", ar:"ستائر خشبية", sub:"Natural blinds", rooms:["Living room","Office","Bedroom"], materials:[["Natural wood","خشب طبيعي"],["Faux wood","خشب صناعي"]], options:[option("Standard","قياسي",180,720)] },
  { slug:"roman-blinds", collection:"blinds", en:"Roman Blinds", ar:"ستائر رومانية", sub:"Fabric blinds", rooms:["Living room","Bedroom","Dining room"], materials:curtainMaterials, motor:true, options:[option("Standard","قياسي",130,520),option("Motorized","آلية بمحرك",300,1200,true)] },

  { slug:"ring-curtains", collection:"curtains", en:"Ring Curtains", ar:"ستائر بحلقات", sub:"Heading style", rooms:["Living room","Bedroom"], materials:curtainMaterials, options:[option("Curtains Only","ستائر فقط",70,560),option("Sheers Only","شفافة فقط",50,400),option("Curtains + Sheers","ستائر وشفافة",110,880)] },
  { slug:"eyelet-curtains", collection:"curtains", en:"Eyelet Curtains", ar:"ستائر بعيون معدنية", sub:"Heading style", rooms:["Living room","Bedroom"], materials:curtainMaterials, options:[option("Curtains Only","ستائر فقط",80,640),option("Sheers Only","شفافة فقط",60,480),option("Curtains + Sheers","ستائر وشفافة",130,1040)] },
  { slug:"pinch-pleat-curtains", collection:"curtains", en:"Pinch Pleat Curtains", ar:"ستائر بكسرات مضغوطة", sub:"Heading style", rooms:["Living room","Bedroom","Dining room"], materials:curtainMaterials, motor:true, featured:true, options:[option("Curtains Only","ستائر فقط",70,560),option("Sheers Only","شفافة فقط",50,400),option("Curtains + Sheers","ستائر وشفافة",110,880),option("Motorized Curtains","ستائر بمحرك",190,1520,true),option("Motorized Sheers","شفافة بمحرك",170,1360,true),option("Motorized Both","كلاهما بمحرك",330,2640,true)] },
  { slug:"ripplefold-curtains", collection:"curtains", en:"Ripplefold Curtains", ar:"ستائر ريبلفولد", sub:"Heading style", rooms:["Living room","Bedroom","Hotel"], materials:curtainMaterials, motor:true, options:[option("Curtains Only","ستائر فقط",85,680),option("Sheers Only","شفافة فقط",55,440),option("Curtains + Sheers","ستائر وشفافة",140,1120),option("Motorized Curtains","ستائر بمحرك",220,1760,true),option("Motorized Sheers","شفافة بمحرك",200,1600,true),option("Motorized Both","كلاهما بمحرك",400,3200,true)] },
  { slug:"loop-curtains", collection:"curtains", en:"Loop Curtains", ar:"ستائر بحلقات قماشية", sub:"Heading style", rooms:["Bedroom","Living room"], materials:curtainMaterials, options:[option("Curtains Only","ستائر فقط",75,600),option("Sheers Only","شفافة فقط",50,400),option("Curtains + Sheers","ستائر وشفافة",110,880)] },
  { slug:"blackout-curtains", collection:"curtains", en:"Blackout Curtains", ar:"ستائر تعتيم", sub:"Performance curtain", rooms:["Bedroom","Nursery","Home theater"], materials:[["Triple weave","نسيج ثلاثي"],["Foam-backed","بطانة إسفنجية"],["Thermal blackout","تعتيم حراري"]], motor:true, featured:true, options:[option("Blackout Curtains","ستائر تعتيم",80,640),option("Motorized Curtains","ستائر بمحرك",200,1600,true),option("Motorized Sheers","شفافة بمحرك",180,1440,true),option("Motorized Both","كلاهما بمحرك",360,2880,true)] },
  { slug:"sheer-curtains", collection:"curtains", en:"Sheer Curtains", ar:"ستائر شفافة", sub:"Fabric", rooms:["Living room","Dining room","Bedroom"], materials:[["Voile","فوال"],["Sheer weave","نسيج شفاف"],["Jacquard","جاكار"]], motor:true, options:[option("Plain Sheers","شفافة سادة",70,560),option("Sheer + Curtain","شفافة وستارة",160,1280),option("Motorized Sheers","شفافة بمحرك",170,1360,true)] },
  { slug:"linen-curtains", collection:"curtains", en:"Linen Curtains", ar:"ستائر كتانية", sub:"Fabric", rooms:["Living room","Bedroom"], materials:[["Linen finish","تشطيب كتاني"],["Cotton blend","مزيج قطني"],["Sheer linen","كتان شفاف"]], motor:true, options:[option("Linen Curtain","ستارة كتانية",90,720),option("Sheer","شفافة",70,560),option("Sheer + Curtain","شفافة وستارة",160,1280),option("Blackout Curtain","ستارة تعتيم",120,960),option("Motorized Curtain","ستارة بمحرك",200,1600,true),option("Motorized Sheer","شفافة بمحرك",180,1440,true),option("Motorized Both","كلاهما بمحرك",360,2880,true)] },
  { slug:"velvet-curtains", collection:"curtains", en:"Velvet Curtains", ar:"ستائر مخملية", sub:"Fabric", rooms:["Bedroom","Living room","Dining room"], materials:[["Cotton velvet","مخمل قطني"],["Silk finish","تشطيب حريري"],["Performance velvet","مخمل عملي"]], options:[option("Plain Velvet Curtain","مخمل سادة",70,560),option("Printed Velvet","مخمل مطبوع",100,800),option("Velvet Blackout","مخمل معتم",100,800)] },
  { slug:"kids-room-curtains", collection:"curtains", en:"Kids Room Curtains", ar:"ستائر غرف الأطفال", sub:"Room solution", rooms:["Kids room","Nursery"], materials:[["Cotton","قطن"],["Blackout","تعتيم"],["Easy-clean fabric","قماش سهل التنظيف"]], motor:true, options:[option("Kids Curtains","ستائر أطفال",70,560),option("Kids Blackout","تعتيم أطفال",80,640),option("Motorized Curtains","ستائر بمحرك",190,1520,true)] },
  { slug:"bedroom-curtains", collection:"curtains", en:"Bedroom Curtains", ar:"ستائر غرف النوم", sub:"Room solution", rooms:["Bedroom"], materials:curtainMaterials, motor:true, options:[option("Curtains Only","ستائر فقط",70,560),option("Sheers Only","شفافة فقط",50,400),option("Curtains + Sheers","ستائر وشفافة",110,880),option("Motorized Curtains","ستائر بمحرك",190,1520,true)] },
  { slug:"living-room-curtains", collection:"curtains", en:"Living Room Curtains", ar:"ستائر غرف المعيشة", sub:"Room solution", rooms:["Living room"], materials:curtainMaterials, motor:true, options:[option("Curtains Only","ستائر فقط",70,560),option("Sheers Only","شفافة فقط",50,400),option("Curtains + Sheers","ستائر وشفافة",110,880),option("Motorized Curtains","ستائر بمحرك",190,1520,true)] },
  { slug:"curtain-installation", collection:"curtains", en:"Curtain Fixing & Installation", ar:"تركيب وتثبيت الستائر", sub:"Installation", rooms:["All rooms"], materials:[["Track systems","أنظمة مسارات"],["Poles and brackets","قضبان وحوامل"],["Motor systems","أنظمة محركات"]], motor:true, options:[option("Per Window","لكل نافذة",150,150),option("Per Linear Meter","لكل متر طولي",25,100),option("Motor (per motor)","المحرك (لكل محرك)",520,520,true)] },

  { slug:"sofa-set-upholstery", collection:"indoor-upholstery", en:"Sofa Set Upholstery", ar:"تنجيد طقم أريكة", sub:"Indoor upholstery", rooms:["Living room","Majlis"], materials:indoorMaterials, featured:true },
  { slug:"bed-upholstery", collection:"indoor-upholstery", en:"Bed Upholstery", ar:"تنجيد السرير", sub:"Indoor upholstery", rooms:["Bedroom"], materials:indoorMaterials },
  { slug:"chair-upholstery", collection:"indoor-upholstery", en:"Chairs Upholstery", ar:"تنجيد الكراسي", sub:"Indoor upholstery", rooms:["Dining room","Living room","Office"], materials:indoorMaterials },
  { slug:"cushion-upholstery", collection:"indoor-upholstery", en:"Cushions Upholstery", ar:"تنجيد الوسائد", sub:"Indoor upholstery", rooms:["Living room","Bedroom"], materials:indoorMaterials },
  { slug:"headboard-upholstery", collection:"indoor-upholstery", en:"Headboard Upholstery", ar:"تنجيد لوح رأس السرير", sub:"Indoor upholstery", rooms:["Bedroom"], materials:indoorMaterials },
  { slug:"wall-panel-upholstery", collection:"indoor-upholstery", en:"Wall Panels Upholstery", ar:"تنجيد ألواح الجدران", sub:"Indoor upholstery", rooms:["Bedroom","Living room","Office"], materials:indoorMaterials },
  { slug:"bedbase-upholstery", collection:"indoor-upholstery", en:"Bedbase Upholstery", ar:"تنجيد قاعدة السرير", sub:"Indoor upholstery", rooms:["Bedroom"], materials:indoorMaterials },
  { slug:"sponge-repairing", collection:"indoor-upholstery", en:"Sponge Repairing & Filling", ar:"إصلاح وحشو الإسفنج", sub:"Repair", rooms:["Living room","Bedroom","Office"], materials:[["High-density foam","إسفنج عالي الكثافة"],["Memory foam","إسفنج ذاكرة"],["Fiber filling","حشوة ألياف"]] },

  { slug:"outdoor-cushions", collection:"outdoor-upholstery", en:"Outdoor Cushions", ar:"وسائد خارجية", sub:"Outdoor upholstery", rooms:["Terrace","Garden","Balcony"], materials:outdoorMaterials, featured:true },
  { slug:"sunbed-cushions", collection:"outdoor-upholstery", en:"Outdoor Sunbed Cushions", ar:"وسائد أسرّة التشمس", sub:"Outdoor upholstery", rooms:["Poolside","Terrace"], materials:outdoorMaterials },
  { slug:"outdoor-sofa-cushions", collection:"outdoor-upholstery", en:"Outdoor Sofa Cushions", ar:"وسائد الأرائك الخارجية", sub:"Outdoor upholstery", rooms:["Terrace","Garden"], materials:outdoorMaterials },
  { slug:"outdoor-furniture-upholstery", collection:"outdoor-upholstery", en:"Outdoor Furniture Upholstery", ar:"تنجيد الأثاث الخارجي", sub:"Outdoor upholstery", rooms:["Terrace","Garden","Poolside"], materials:outdoorMaterials },
  { slug:"outdoor-cushions-manufacturing", collection:"outdoor-upholstery", en:"Outdoor Cushions Manufacturing", ar:"تصنيع الوسائد الخارجية", sub:"Manufacturing", rooms:["Terrace","Garden","Poolside"], materials:outdoorMaterials },
  { slug:"outdoor-protection-cover", collection:"outdoor-upholstery", en:"Custom Outdoor Protection Cover", ar:"غطاء حماية خارجي حسب الطلب", sub:"Protection", rooms:["Terrace","Garden","Poolside"], materials:[["Water-resistant textile","نسيج مقاوم للماء"],["UV-stable fabric","قماش مقاوم للأشعة"],["Breathable lining","بطانة قابلة للتنفس"]] },

  { slug:"handleless-contemporary-kitchen", collection:"kitchen-cabinets", en:"Handleless Contemporary Kitchen", ar:"مطبخ عصري بدون مقابض", sub:"Contemporary cabinetry", rooms:["Kitchen","Apartment"], materials:[["Lacquered MDF","ألواح إم دي إف مطلية"],["Fluted glass","زجاج مخدد"],["Marble-look porcelain","بورسلان بمظهر الرخام"],["Integrated lighting","إضاءة مدمجة"],["Quartz surfaces","أسطح كوارتز"],["Integrated profiles","حواف مدمجة"]], featured:true, summary:t("A versatile handleless kitchen family combining seamless storage, U-shaped planning, marble-look surfaces and illuminated glass detail.","مجموعة مطابخ عصرية بدون مقابض تجمع التخزين الانسيابي والتخطيط على شكل حرف U والأسطح بمظهر الرخام والتفاصيل الزجاجية المضاءة."), description:t("These coordinated contemporary kitchens share the same clean architectural language: handleless fronts, integrated appliances, carefully aligned work surfaces and optional illuminated fluted-glass display cabinets. The layout is tailored to the room, from a compact galley to a practical U-shaped apartment kitchen.","تتشارك هذه المطابخ العصرية لغة معمارية نظيفة تشمل واجهات بدون مقابض وأجهزة مدمجة وأسطح عمل محاذية بعناية وخزائن عرض اختيارية من الزجاج المخدد المضاء. ويتم تخصيص التخطيط حسب المساحة، من مطبخ ممر مدمج إلى مطبخ شقة عملي على شكل حرف U."), images:["/images/catalog/handleless-contemporary-kitchen.webp","/images/catalog/kitchens/combined-compact-galley-kitchen.webp","/images/catalog/kitchens/combined-u-shaped-kitchen.webp","/images/catalog/kitchens/combined-illuminated-glass-kitchen.webp","/images/catalog/kitchens/combined-glass-detail-kitchen.webp","/images/catalog/kitchens/handleless-contemporary-kitchen-2.webp","/images/catalog/kitchens/glass-detail-kitchen-cabinetry-2.webp","/images/catalog/kitchens/kitchen-cabinets-inspiration-1.webp"] },
  { slug:"full-height-kitchen-storage", collection:"kitchen-cabinets", en:"Full-Height Storage & Pantry", ar:"خزائن تخزين وبانتري بارتفاع كامل", sub:"Kitchen and appliance storage", rooms:["Kitchen","Pantry"], materials:[["Moisture-resistant MDF","ألواح إم دي إف مقاومة للرطوبة"],["Lacquered MDF","ألواح إم دي إف مطلية"],["Adjustable shelving","رفوف قابلة للتعديل"],["Tinted glass","زجاج ملون"],["Integrated appliance bay","مساحة جهاز مدمجة"],["Soft-close hardware","مفصلات إغلاق هادئ"]], summary:t("A tailored pantry family combining floor-to-ceiling storage, efficient corner shelving and an integrated appliance niche.","مجموعة بانتري مصممة حسب المساحة تجمع التخزين من الأرض إلى السقف ورفوف الزاوية العملية وتجويفاً مدمجاً للأجهزة."), description:t("Every shelf, corner compartment, appliance bay and internal fitting is planned around what the household needs to store. Concealed full-height doors, adjustable shelving, glazed display sections and a dedicated microwave niche can be combined into one quiet, space-efficient composition.","يتم تخطيط كل رف ووحدة زاوية ومساحة جهاز وتجهيز داخلي وفق احتياجات المنزل. ويمكن جمع الأبواب المخفية بارتفاع كامل والرفوف القابلة للتعديل ووحدات العرض الزجاجية وتجويف الميكروويف المخصص في تكوين هادئ وموفر للمساحة."), images:["/images/catalog/full-height-kitchen-storage.webp","/images/catalog/kitchens/combined-corner-pantry-storage.webp","/images/catalog/kitchens/combined-integrated-microwave-pantry.webp","/images/catalog/kitchens/full-height-kitchen-storage-2.webp","/images/catalog/kitchens/kitchen-cabinets-inspiration-2.webp"] },
  { slug:"glass-panel-classic-kitchen", collection:"kitchen-cabinets", en:"Glass-Panel Classic Kitchen", ar:"مطبخ كلاسيكي بواجهات زجاجية", sub:"Glass-front cabinetry", rooms:["Kitchen"], materials:[["Painted MDF","ألواح إم دي إف مطلية"],["Frosted glass","زجاج مصنفر"],["Marble-look surface","سطح بمظهر الرخام"],["Brass handles","مقابض نحاسية"]], summary:t("A bright U-shaped kitchen pairing framed glass doors with warm brass detailing.","مطبخ مشرق على شكل حرف U يجمع بين الأبواب الزجاجية المؤطرة والتفاصيل النحاسية الدافئة."), description:t("Framed upper and lower cabinets introduce display, rhythm and traditional detail while maintaining practical worktop space. Frosted glazing, pale marble-look surfaces and brass handles create a light, coordinated composition.","تضيف الخزائن العلوية والسفلية المؤطرة مساحات عرض وإيقاعاً بصرياً وتفاصيل كلاسيكية مع الحفاظ على سطح عمل عملي. ويمنح الزجاج المصنفر والأسطح الفاتحة بمظهر الرخام والمقابض النحاسية تكويناً متناسقاً ومشرقاً.") },
  { slug:"full-width-minimal-upper-cabinetry", collection:"kitchen-cabinets", en:"Full-Width Minimal Upper Cabinetry", ar:"خزائن علوية بسيطة بعرض كامل", sub:"Minimal cabinetry", rooms:["Kitchen","Dining room"], materials:[["Matte lacquer","طلاء مطفي"],["Handleless fronts","واجهات بدون مقابض"],["Integrated profiles","حواف مدمجة"],["Quartz island surface","سطح جزيرة كوارتز"]], summary:t("A continuous run of minimal upper cabinets gives a broad kitchen wall a calm architectural line.","صف متصل من الخزائن العلوية البسيطة يمنح جدار المطبخ الواسع خطاً معمارياً هادئاً."), description:t("Flush doors and carefully aligned proportions create generous concealed storage without visual noise. The uninterrupted upper run works with the island and lower cabinetry as one measured composition.","توفر الأبواب المستوية والنسب المحاذية بعناية تخزيناً مخفياً واسعاً دون ازدحام بصري. ويتكامل الصف العلوي المتصل مع الجزيرة والخزائن السفلية كتكوين واحد مدروس.") },
  { slug:"graphite-contemporary-kitchen", collection:"kitchen-cabinets", en:"Graphite Contemporary Kitchen", ar:"مطبخ عصري بلون الجرافيت", sub:"Contemporary cabinetry", rooms:["Kitchen"], materials:[["Matte graphite fronts","واجهات جرافيت مطفية"],["Stone-look splashback","جدار خلفي بمظهر الحجر"],["Integrated lighting","إضاءة مدمجة"],["Solid work surface","سطح عمل صلب"]], summary:t("Graphite cabinetry and layered task lighting give a compact kitchen a confident contemporary character.","خزائن الجرافيت وإضاءة العمل المتدرجة تمنح المطبخ المدمج طابعاً عصرياً واثقاً."), description:t("Dark matte fronts frame a practical U-shaped plan with integrated drawers, tall storage and illuminated preparation areas. Contrasting stone-look finishes keep the composition balanced and durable for daily use.","تؤطر الواجهات الداكنة المطفية مخططاً عملياً على شكل حرف U مع أدراج مدمجة وتخزين طويل ومناطق تحضير مضاءة. وتحافظ التشطيبات المتباينة بمظهر الحجر على توازن التكوين ومتانته للاستخدام اليومي.") },
  { slug:"symmetrical-appliance-wall-kitchen", collection:"kitchen-cabinets", en:"Symmetrical Appliance-Wall Kitchen", ar:"مطبخ بجدار أجهزة متناظر", sub:"Integrated appliance cabinetry", rooms:["Kitchen","Apartment"], materials:[["Matte lacquer fronts","واجهات مطلية مطفية"],["Full-height storage","تخزين بارتفاع كامل"],["Integrated appliance housing","وحدات أجهزة مدمجة"],["Solid-surface worktop","سطح عمل صلب"]], summary:t("A balanced appliance wall combines tall storage, preparation space and integrated cooking in one precise elevation.","جدار أجهزة متوازن يجمع التخزين الطويل ومساحة التحضير والطهي المدمج في واجهة دقيقة واحدة."), description:t("Full-height cabinets anchor both sides of the composition while centered cooking appliances and wide drawers keep the work zone orderly. The symmetrical layout is especially effective where a single wall must carry most kitchen functions.","تثبت الخزائن بارتفاع كامل جانبي التكوين، بينما تحافظ أجهزة الطهي المركزية والأدراج الواسعة على تنظيم منطقة العمل. ويعد التخطيط المتناظر فعالاً خصوصاً عندما يحمل جدار واحد معظم وظائف المطبخ.") },

  { slug:"marble-look-porcelain-tiles", collection:"washroom-tiles", en:"Marble-Look Porcelain Tiles", ar:"بلاط بورسلان بمظهر الرخام", sub:"Large-format porcelain", rooms:["Bathroom","Ensuite","Powder room"], materials:[["Large-format porcelain","بورسلان كبير المقاس"],["Book-matched look","مظهر عروق متطابقة"],["Low-slip floor finish","تشطيب أرضي مقاوم للانزلاق"],["Coordinated grout","جراوت متناسق"]], featured:true, summary:t("The quiet luxury of veined stone with the practical consistency of porcelain.","فخامة هادئة لعروق الحجر مع العملية والثبات اللذين يوفرهما البورسلان."), description:t("Large-format porcelain creates a calm, continuous washroom surface with fewer visual breaks. We help coordinate pattern direction, wall and floor formats, grout tone, setting-out and professional installation around the room.","يمنح البورسلان كبير المقاس الحمام سطحاً هادئاً ومتواصلاً مع فواصل بصرية أقل. ننسق اتجاه العروق ومقاسات الجدران والأرضيات ولون الجراوت وتخطيط التركيب والتنفيذ الاحترافي."), images:["/images/catalog/marble-look-porcelain-tiles.webp","/images/catalog/washrooms/natural-stone-look-tiles.webp"] },
  { slug:"natural-stone-look-tiles", collection:"washroom-tiles", en:"Natural Stone-Look Tiles", ar:"بلاط بمظهر الحجر الطبيعي", sub:"Textured porcelain", rooms:["Bathroom","Ensuite","Shower room"], materials:[["Stone-look porcelain","بورسلان بمظهر الحجر"],["Textured finish","تشطيب ملمسي"],["Coordinated trims","حواف متناسقة"],["Low-slip floor option","خيار أرضي مقاوم للانزلاق"]], summary:t("Warm, tactile surfaces that bring spa-like calm to everyday washrooms.","أسطح دافئة وملمسية تضيف هدوء المنتجعات الصحية إلى الحمامات اليومية."), description:t("Layered stone tones give walls, floors and shower zones a grounded architectural character. Our service connects selection with site assessment, preparation, setting-out, careful cutting, installation, grouting and finishing.","تمنح درجات الحجر المتناسقة الجدران والأرضيات ومناطق الاستحمام طابعاً معمارياً هادئاً. تربط خدمتنا الاختيار بمعاينة الموقع والتحضير والتخطيط والقص الدقيق والتركيب والجراوت والتشطيب."), images:["/images/catalog/natural-stone-look-tiles.webp","/images/catalog/washrooms/marble-look-porcelain-tiles.webp"] },
  { slug:"feature-mosaic-tiles", collection:"washroom-tiles", en:"Feature & Mosaic Tiles", ar:"بلاط مميز وفسيفساء", sub:"Decorative tile", rooms:["Powder room","Bathroom","Shower niche"], materials:[["Porcelain mosaic","فسيفساء بورسلان"],["Ceramic feature tile","بلاط سيراميك مميز"],["Metal trims","حواف معدنية"],["Colour-matched grout","جراوت متناسق اللون"]], summary:t("A considered focal surface for feature walls, niches and precisely framed details.","سطح محوري مدروس للجدران المميزة والتجاويف والتفاصيل المؤطرة بدقة."), description:t("Mosaic and small-format tiles introduce rhythm and detail without overwhelming the room. We resolve scale, alignment, edge trims and grout colour alongside the surrounding large-format surfaces for a balanced finish.","تضيف الفسيفساء والبلاطات الصغيرة إيقاعاً وتفصيلاً دون إثقال المساحة. ننسق المقاس والمحاذاة وحواف التشطيب ولون الجراوت مع الأسطح الكبيرة المحيطة لنتيجة متوازنة."), images:["/images/catalog/feature-mosaic-tiles.webp","/images/catalog/washrooms/marble-look-porcelain-tiles.webp"] },
];

const collectionNames: Record<CatalogOffering["collection"], LocalizedText> = {
  "custom-furniture": t("Custom Furniture", "أثاث حسب الطلب"), blinds:t("Blinds", "الستائر العصرية"), curtains:t("Curtains", "الستائر"),
  "indoor-upholstery":t("Indoor Upholstery", "التنجيد الداخلي"), "outdoor-upholstery":t("Outdoor Upholstery", "التنجيد الخارجي"),
  "kitchen-cabinets":t("Kitchen Cabinets", "خزائن المطابخ"), "washroom-tiles":t("Washroom Tiles", "بلاط الحمامات")
};

const galleryCompanion: Record<CatalogOffering["collection"], string> = {
  "custom-furniture": "/images/catalog/editorial/custom-furniture-showroom.webp",
  blinds: "/images/catalog/editorial/window-treatments-showroom.webp",
  curtains: "/images/catalog/editorial/window-treatments-showroom.webp",
  "indoor-upholstery": "/images/catalog/editorial/indoor-upholstery-showroom.webp",
  "outdoor-upholstery": "/images/catalog/editorial/outdoor-upholstery-showroom.webp",
  "kitchen-cabinets": "/images/catalog/kitchens/kitchen-cabinets-detail.webp",
  "washroom-tiles": "/images/catalog/editorial/washroom-finishes-showroom.webp",
};

export const catalog: CatalogOffering[] = seeds.map((seed, index) => {
  const isCustom = seed.collection === "custom-furniture";
  const isUpholstery = seed.collection.includes("upholstery");
  const isNewCollection = seed.collection === "kitchen-cabinets" || seed.collection === "washroom-tiles";
  const pricing = isCustom ? { mode:"tiered" as const, options:[], tiers:[{label:t("Standard","قياسي"),range:"AED 150–300"},{label:t("Premium","فاخر"),range:"AED 300–600"},{label:t("Luxury","فائق الفخامة"),range:"AED 600+"}] } : isUpholstery || isNewCollection ? { mode:"quote" as const, options:[] } : { mode:"per-sqm" as const, options:seed.options || [] };
  const collection = collectionNames[seed.collection];
  const baseImages = seed.images || [`/images/catalog/${seed.slug}.webp`, `/images/collections/${seed.collection}.webp`];
  const images = [...new Set([...baseImages, galleryCompanion[seed.collection]])];
  return {
    slug:seed.slug, collection:seed.collection, subcollection:seed.sub, serviceType:isUpholstery || seed.slug === "curtain-installation" ? "service" : "product",
    name:t(seed.en,seed.ar),
    summary:seed.summary || t(`${seed.en}, measured and made around your space.`, `${seed.ar}، مصمم ومُنفذ بما يناسب مساحتك.`),
    description:seed.description || t(`A considered NESTRO solution balancing appearance, daily performance and precise fit. Our team helps you compare materials, confirm measurements and specify every practical detail before production.`, `حل مدروس من نسترو يجمع بين جمال المظهر والأداء اليومي ودقة المقاس. يساعدك فريقنا على مقارنة الخامات وتأكيد القياسات وتحديد كل التفاصيل العملية قبل التنفيذ.`),
    features:[t("Made to measure","تنفيذ حسب المقاس"),t(seed.motor ? "Manual or motorized operation" : "Tailored material selection","اختيار خامات مخصص"),t("Professional fitting available","تركيب احترافي متاح"),t("Material samples on consultation","عينات خامات أثناء الاستشارة")],
    benefits:[t("A precise fit for the room","ملاءمة دقيقة للمساحة"),t("Clear guidance from selection to installation","إرشاد واضح من الاختيار حتى التركيب"),t("Specified for UAE interiors","مناسب للمساحات الداخلية في الإمارات")],
    idealUses:seed.rooms.map((room)=>t(room, roomArabic[room] || room)),
    materials:seed.materials.map(([en,ar])=>({name:t(en,ar),description:t(`Selected for the requirements of ${seed.en.toLowerCase()}.`,`مختارة لتناسب متطلبات ${seed.ar}.`)})),
    comparisonPoints:[{feature:t("Specification","المواصفات"),value:t("Configured for your dimensions and use","مهيأ لأبعادك وطريقة الاستخدام")},{feature:t("Support","الدعم"),value:t("Measurement, material guidance and fitting","قياس وإرشاد للخامات وتركيب")}],
    faqs:[{question:t(`How is ${seed.en.toLowerCase()} specified?`,`كيف يتم تحديد مواصفات ${seed.ar}؟`),answer:t("We begin with dimensions, use, light or comfort needs, then confirm the material and configuration before quoting.","نبدأ بالأبعاد وطريقة الاستخدام واحتياجات الإضاءة أو الراحة، ثم نؤكد الخامة والتكوين قبل تقديم السعر.")},{question:t("Can I see material samples?","هل يمكنني مشاهدة عينات الخامات؟"),answer:t("Yes. Suitable samples can be reviewed during a consultation before the final specification is approved.","نعم. يمكن مراجعة العينات المناسبة خلال الاستشارة قبل اعتماد المواصفات النهائية.")},{question:t("Is installation included?","هل يشمل السعر التركيب؟"),answer:t("Installation requirements are confirmed in the final proposal because access, dimensions and site conditions vary.","يتم تأكيد متطلبات التركيب في العرض النهائي لاختلاف سهولة الوصول والأبعاد وظروف الموقع.")}],
    pricing, images, rooms:seed.rooms, badges:[collection,t("Made to measure","حسب المقاس")], availability:isNewCollection?"Consultation required":"Made to order", motorization:Boolean(seed.motor), indoorOutdoor:seed.collection === "outdoor-upholstery" ? "outdoor" : "indoor",
    seo:{title:t(`${seed.en} in the UAE`,`${seed.ar} في الإمارات`),description:t(`Explore materials, configurations and indicative pricing for ${seed.en.toLowerCase()} by NESTRO.`,`استكشف الخامات والتكوينات والأسعار الإرشادية لـ${seed.ar} من نسترو.`)},
    related:seeds.filter((x)=>x.collection===seed.collection && x.slug!==seed.slug).slice(0,3).map((x)=>x.slug),
    care:seed.collection === "kitchen-cabinets" ? t("Wipe cabinetry with a soft, lightly damp cloth and dry promptly. Avoid abrasive cleaners, excess water and prolonged heat or steam on finished surfaces.","امسح الخزائن بقطعة قماش ناعمة ورطبة قليلاً ثم جففها مباشرة. تجنب المنظفات الكاشطة والمياه الزائدة والحرارة أو البخار المستمر على الأسطح.") : seed.collection === "washroom-tiles" ? t("Use a pH-neutral cleaner suitable for the approved tile and grout. Avoid abrasive tools and follow the product-specific care instructions supplied at handover.","استخدم منظفاً متعادل الحموضة مناسباً للبلاط والجراوت المعتمدين. تجنب الأدوات الكاشطة واتبع تعليمات العناية الخاصة بالمنتج عند التسليم.") : t("Use a soft brush or low-suction vacuum for routine care. Follow the approved material-specific instructions supplied with your order.","للعناية الدورية استخدم فرشاة ناعمة أو مكنسة بقوة شفط منخفضة، واتبع تعليمات الخامة المرفقة مع طلبك."),
    source:isNewCollection ? {reference:"NESTRO original",captured:"2026-08-20",note:seed.collection === "washroom-tiles" ? "NESTRO-authored copy; temporary original AI-generated presentation imagery pending client photography." : "NESTRO-authored copy and client-authorized project photography."} : {reference:"https://www.gmfdubai.com/",captured:"2026-08-18",note:"One-time factual taxonomy and public pricing audit; NESTRO-authored copy and imagery."},
    featured:seed.featured || index < 2
  };
});

export const catalogCollections = (Object.keys(collectionNames) as CatalogOffering["collection"][]).map((slug)=>({
  slug, name:collectionNames[slug], image:`/images/collections/${slug}.webp`, count:catalog.filter((item)=>item.collection===slug).length
}));

export const bySlug = (slug: string) => catalog.find((item)=>item.slug===slug);
export const localized = (value: LocalizedText, locale: Locale) => value[locale];
export const localizedRoom = (room: string, locale: Locale) => locale === "ar" ? roomArabic[room] || room : room;
export const startingPrice = (item: CatalogOffering) => item.pricing.options.length ? Math.min(...item.pricing.options.map((x)=>x.pricePerSqm)) : null;

export function assertCatalog() {
  const expected = { "custom-furniture":4, blinds:9, curtains:13, "indoor-upholstery":8, "outdoor-upholstery":6, "kitchen-cabinets":6, "washroom-tiles":3 } as const;
  for (const [key,count] of Object.entries(expected)) if (catalog.filter((item)=>item.collection===key).length !== count) throw new Error(`Catalog count mismatch for ${key}`);
  if (new Set(catalog.map((item)=>item.slug)).size !== 49) throw new Error("Catalog slugs must be unique");
  for (const item of catalog) if (!item.name.en || !item.name.ar || !item.description.en || !item.description.ar) throw new Error(`Missing bilingual content: ${item.slug}`);
  return true;
}

assertCatalog();
