import type { Metadata } from "next";
import Image from "next/image";
import Link from "@/components/shared/StaticLink";
import { ArrowRight } from "lucide-react";
import { SectionHeading } from "@/components/shared/SectionHeading";
import { CustomFurnitureWizard } from "@/components/wizard/CustomFurnitureWizard";
import type { Locale } from "@/types";

export const metadata: Metadata = { title: "Custom Furniture UAE", description: "Design made-to-measure sofas, beds, headboards, wardrobes and storage with the NESTRO custom furniture studio." };
const categories = [
  { slug: "sofas", eyebrow: ["Custom sofas", "أرائك حسب الطلب"], name: ["Sofas & seating", "الأرائك والجلسات"], copy: ["Comfort, depth and silhouette tuned precisely to how you sit, host and unwind.", "راحة وعمق وشكل مضبوط بدقة لطريقة جلوسك وضيافتك واسترخائك."], image: "/images/catalog/custom-sofa-chair.webp" },
  { slug: "beds", eyebrow: ["Custom beds", "أسرّة حسب الطلب"], name: ["Beds & headboards", "الأسرّة وألواح الرأس"], copy: ["Restful proportions, tailored upholstery and tactile details built around your bedroom.", "نسب مريحة وتنجيد مفصل وتفاصيل غنية بالملمس مصممة حول غرفة نومك."], image: "/images/catalog/custom-bed-headboard.webp" },
  { slug: "wardrobes", eyebrow: ["Custom storage", "تخزين حسب الطلب"], name: ["Wardrobes & storage", "الخزائن ووحدات التخزين"], copy: ["Architectural storage shaped around your habits and space.", "حلول تخزين معمارية تتشكل حول عاداتك ومساحتك."], image: "/images/catalog/wardrobe-cabinet.webp" },
];

export function CustomFurnitureView({ locale = "en" }: { locale?: Locale }) {
  const ar = locale === "ar", prefix = ar ? "/ar" : "", value = (pair: string[]) => pair[ar ? 1 : 0];
  return <div dir={ar ? "rtl" : "ltr"}>
    <section className="container-site grid gap-10 py-14 lg:grid-cols-2 lg:items-center lg:py-24"><div><span className="eyebrow">{ar ? "الاستوديو المخصص" : "The custom studio"}</span><h1 className="display mt-6">{ar ? <>مصمم حول<br />طريقة حياتك.</> : <>Made around<br />the way you live.</>}</h1><p className="subheading mt-7">{ar ? "خدمة تصميم تعاونية لأثاث يتمتع بالمقاس والراحة والخامة والطابع الصحيح، لأن القريب من المطلوب لا يساوي قطعة تخصك." : "A collaborative design service for furniture with the right scale, comfort, material and character—because almost right is not the same as yours."}</p><Link href="#wizard" className="button button-primary mt-8">{ar ? "ابدأ موجز مشروعك" : "Begin your brief"} <ArrowRight className={ar ? "rotate-180" : ""} size={16} /></Link></div><div className="card-image relative aspect-[5/4] overflow-hidden rounded-3xl"><Image src="/images/collections/custom-furniture.webp" alt={ar ? "تصميم داخلي مخصص من NESTRO" : "Bespoke NESTRO interior"} fill priority className="object-cover" /></div></section>
    <section className="section section-soft pb-8"><div className="container-site text-center"><SectionHeading eyebrow={ar ? "ما نصنعه" : "What we make"} title={ar ? "خدمة متخصصة لكل قطعة." : "A dedicated service for every piece."} copy={ar ? "استكشف الأرائك والأسرّة والتخزين كل على حدة، بخدمة تتشكل حول متطلبات الراحة والبناء والمساحة لكل فئة." : "Explore sofas, beds and storage separately, with each service shaped around its own comfort, construction and spatial requirements."} align="center" /></div></section>
    {categories.map((category, index) => <section key={category.slug} className={index % 2 === 0 ? "section section-soft pt-8" : "section section-light"}><div className="container-site grid gap-8 lg:grid-cols-2 lg:items-center lg:gap-14"><div className={index % 2 === 1 ? "lg:order-2" : undefined}><span className="eyebrow">{value(category.eyebrow)}</span><h2 className="heading mt-5">{value(category.name)}</h2><p className="mt-5 max-w-xl text-base leading-7 text-black/60">{value(category.copy)}</p><Link href={`${prefix}/custom-furniture/${category.slug}`} className="button button-primary mt-7 w-fit">{ar ? `استكشف ${value(category.name)}` : `Explore ${value(category.name).toLowerCase()}`} <ArrowRight className={ar ? "rotate-180" : ""} size={16} /></Link></div><Link href={`${prefix}/custom-furniture/${category.slug}`} className={`card-image interactive-card relative aspect-[5/4] overflow-hidden rounded-3xl ${index % 2 === 1 ? "lg:order-1" : ""}`} aria-label={ar ? `استكشف ${value(category.name)}` : `Explore ${value(category.name)}`}><Image src={category.image} alt={value(category.name)} fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /></Link></div></section>)}
    <section id="wizard" className="section section-soft scroll-mt-24"><div className="container-site grid gap-12 lg:grid-cols-[.6fr_1.4fr]"><SectionHeading eyebrow={ar ? "أنشئ موجزك" : "Create your brief"} title={ar ? "ابدأ بما تعرفه." : "Start with what you know."} copy={ar ? "خمس خطوات بسيطة تمنح فريق التصميم لدينا سياقاً كافياً لمحادثة أولى مفيدة. لا شيء هنا يلزمك بقرار نهائي." : "Five simple steps give our design team enough context for a useful first conversation. Nothing here locks you in."} /><CustomFurnitureWizard locale={locale} /></div></section>
  </div>;
}
