import type { Metadata } from "next";
import Image from "next/image";
import Link from "@/components/shared/StaticLink";
import { ArrowRight, Building2, Hotel, House, Presentation } from "lucide-react";
import { ConsultationButton } from "@/components/shared/ClientActions";
import { SectionHeading } from "@/components/shared/SectionHeading";
import type { Locale } from "@/types";

export const metadata: Metadata = { title: "Interior Solutions UAE", description: "NESTRO interior solutions for UAE residences, hospitality spaces, offices and commercial projects." };
const sectors = [
  { icon: House, title: ["Residential", "سكني"], copy: ["Complete villa and apartment interiors, from spatial direction to the last textile.", "تصميمات داخلية متكاملة للفلل والشقق، من توجيه المساحة إلى آخر قطعة نسيج."] },
  { icon: Hotel, title: ["Hospitality", "الضيافة"], copy: ["Guest-focused environments balancing character, durability and operational detail.", "بيئات تركز على الضيف وتوازن بين الطابع والمتانة والتفاصيل التشغيلية."] },
  { icon: Presentation, title: ["Office", "المكاتب"], copy: ["Workplaces that feel composed, support focus and welcome clients beautifully.", "مساحات عمل متزنة تدعم التركيز وترحب بالعملاء بأناقة."] },
  { icon: Building2, title: ["Commercial", "تجاري"], copy: ["Joinery, furniture and fit-out support for designers, architects and developers.", "دعم النجارة والأثاث والتجهيز للمصممين والمعماريين والمطورين."] },
];
const atelier = [
  ["sofa-set-upholstery", "Sofa restoration", "ترميم الأرائك", "/images/catalog/sofa-set-upholstery.webp"],
  ["headboard-upholstery", "Custom headboards", "ألواح رأس حسب الطلب", "/images/catalog/headboard-upholstery.webp"],
  ["outdoor-cushions", "Outdoor upholstery", "تنجيد خارجي", "/images/catalog/outdoor-cushions.webp"],
];

export function InteriorSolutionsView({ locale = "en" }: { locale?: Locale }) {
  const ar = locale === "ar", prefix = ar ? "/ar" : "", value = (pair: string[]) => pair[ar ? 1 : 0];
  const tradeItems = ar ? ["مخططات تنفيذية وعينات", "تطوير النماذج الأولية", "إنتاج بالكميات", "تنسيق الموقع", "تركيب في أنحاء الإمارات", "نقطة اتصال واحدة"] : ["Shop drawings & samples", "Prototype development", "Volume production", "Site coordination", "UAE-wide installation", "Single point of contact"];
  return <div dir={ar ? "rtl" : "ltr"}>
    <section className="relative min-h-[680px] overflow-hidden bg-charcoal text-white"><Image src="/images/collections/custom-furniture.webp" alt={ar ? "تصميم داخلي متكامل من NESTRO" : "NESTRO complete interior"} fill priority className="object-cover opacity-70" /><div className="photo-overlay absolute inset-0" /><div className="container-site relative flex min-h-[680px] items-end py-16 md:items-center"><div className="max-w-3xl"><span className="text-xs font-bold uppercase tracking-[.2em] text-white/65">{ar ? "حلول داخلية" : "Interior solutions"}</span><h1 className="display mt-6">{ar ? <>رؤية واحدة.<br />لكل تفصيل.</> : <>One vision.<br />Every detail.</>}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">{ar ? "تصميمات داخلية متكاملة للمنازل والأعمال، تجمع تخطيط المساحة والأثاث حسب الطلب والنجارة والمنسوجات والتركيب ضمن عملية واحدة مدروسة." : "Integrated interiors for homes and businesses, bringing space planning, custom furniture, joinery, textiles and installation into one considered process."}</p><ConsultationButton className="button mt-8 bg-ivory text-charcoal">{ar ? "ناقش مشروعك" : "Discuss your project"}</ConsultationButton></div></div></section>
    <section className="section"><div className="container-site"><SectionHeading eyebrow={ar ? "من نعمل معهم" : "Who we work with"} title={ar ? "منازل شخصية. ومساحات احترافية." : "Personal homes. Professional spaces."} copy={ar ? "يتكيف فريقنا مع نطاق المشروع مع الحفاظ على الوضوح والجودة والدفء الذي يميز NESTRO." : "Our team scales to the brief while protecting the clarity, quality and warmth that define NESTRO."} /><div className="mt-12 grid gap-4 md:grid-cols-4">{sectors.map((sector) => <div key={value(sector.title)} className="surface-card interactive-card p-7"><sector.icon className="text-sage" /><h2 className="mt-7 text-xl font-medium">{value(sector.title)}</h2><p className="mt-3 text-sm leading-6 text-black/55">{value(sector.copy)}</p></div>)}</div></div></section>
    <section className="section section-soft"><div className="container-site grid gap-10 lg:grid-cols-2 lg:items-center"><div className="card-image relative aspect-[5/4] overflow-hidden rounded-2xl"><Image src="/images/catalog/wall-tv-unit.webp" alt={ar ? "نجارة داخلية مخصصة من NESTRO" : "NESTRO custom interior joinery"} fill className="object-cover" /></div><div><span className="eyebrow">{ar ? "للمحترفين" : "For the trade"}</span><h2 className="heading mt-5">{ar ? "شريك قادر على تنفيذ رؤيتك التصميمية." : "A capable partner for your design intent."}</h2><p className="subheading mt-6">{ar ? "ندعم المعماريين ومصممي الديكور والمطورين بالتصنيع المخصص وتوريد الخامات والتنجيد ومعالجات النوافذ والتركيب المنسق في الموقع." : "We support architects, interior designers and developers with custom manufacturing, material sourcing, upholstery, window treatments and coordinated site installation."}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{tradeItems.map((item) => <p key={item} className="border-b fine-border py-3 text-sm">{item}</p>)}</div><ConsultationButton className="button button-dark mt-8">{ar ? "ابدأ استفساراً تجارياً" : "Start a trade enquiry"}</ConsultationButton></div></div></section>
    <section className="section"><div className="container-site"><div className="flex items-end justify-between"><SectionHeading eyebrow={ar ? "مشغل التنجيد" : "The upholstery atelier"} title={ar ? "احتفظ بما يستحق البقاء." : "Keep what is worth keeping."} copy={ar ? "من ترميم الأرائك بالكامل إلى ألواح الرأس والوسائد الخارجية، نعيد بناء الراحة بدقة الورشة." : "From full sofa restoration to headboards and outdoor cushions, we rebuild comfort with workshop precision."} /><Link href={`${prefix}/shop?collection=indoor-upholstery`} className="hidden items-center gap-2 text-sm font-semibold sm:flex">{ar ? "استكشف" : "Explore"} <ArrowRight className={ar ? "rotate-180" : ""} size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{atelier.map(([slug, en, arabic, image]) => <Link href={`${prefix}/shop/${slug}`} key={slug} className="group surface-card interactive-card overflow-hidden"><div className="card-image relative aspect-[4/5]"><Image src={image} alt={ar ? arabic : en} fill className="object-cover" /><div className="photo-overlay-bottom absolute inset-0" /><h3 className="absolute bottom-5 start-5 text-2xl font-medium text-white">{ar ? arabic : en}</h3></div></Link>)}</div></div></section>
  </div>;
}
